In [1]:
import numpy as np

# 2.2 Creating arrays: from lists and using built-in functions

In [3]:
# arrays from lists
distances = [10, 15, 17, 26, 20]
times = [0.3, 0.47, 0.55, 1.20, 1.0]
distances = np.array(distances)
times = np.array(times)

In [5]:
product_quantities = [13, 5, 6, 10, 11]
prices = [1.2, 6.5, 1.0, 4.8, 5.0]
product_quantities = np.array(product_quantities)
prices = np.array(prices)

In [6]:
distances

array([10, 15, 17, 26, 20])

In [7]:
type(distances)

numpy.ndarray

If we pass np.array() a list of lists, it will create a 2-dimensional array. If we pass a list of lists of lists, it will create a 3-dimensional array, and so on and so forth.

In [8]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [9]:
# Create a lenght-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones
np.ones(shape = (3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# Create an arra filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
np.arange(start = 0, stop = 20, step = 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of 20 values evenly spaced between 0 and 1
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# 2.3 Some attributes of arrays

In [12]:
A = np.ones(shape = (3, 4), dtype = float)
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
A.ndim

2

In [15]:
A.shape

(3, 4)

In [16]:
A.size

12

# 2.4 Basic Math with arrays

In [20]:
distances = np.array([10, 15, 17, 26, 20])

times = np.array([0.3, 0.47, 0.55, 1.20, 1.0])

In [21]:
speed = distances/times
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667, 20.        ])

In [22]:
proudct_quantities = np.array([13, 5, 6, 10, 11])

prices = np.array([1.2, 6.5, 1.0, 4.8, 5.0])

In [23]:
values = product_quantities * prices
total = values.sum()

print(values)
total

[15.6 32.5  6.  48.  55. ]


157.1

In [26]:
x = np.arange(start = 0, stop= 20, step = 2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
x + 1 

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
x * 2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [29]:
x / 2

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
# Universal functions
np.sin(x)

array([ 0.        ,  0.90929743, -0.7568025 , -0.2794155 ,  0.98935825,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

In [31]:
np.exp(x)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [32]:
np.log(x+1)

array([0.        , 1.09861229, 1.60943791, 1.94591015, 2.19722458,
       2.39789527, 2.56494936, 2.7080502 , 2.83321334, 2.94443898])

In [33]:
np.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

# 2.5 Common manipulations: indexing, slicing and reshaping

### 2.5.1 Indexing: Getting and setting the value of individual array elements

In [35]:
one_dim = np.linspace(-0.5, 0.6, 12)
one_dim

array([-0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [41]:
one_dim[0] = 1
one_dim[5]
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [38]:
two_dim = np.array([[3, 5, 2, 4],[7, 6, 5, 5], [1, 6, -1, -1]])
two_dim

array([[ 3,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [42]:
two_dim[0, 3]

4

In [43]:
two_dim[0,0] = -1
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

### 2.5.2 Slicing: Getting and setting smaller subarrays within a larger array

In [45]:
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [44]:
print(one_dim[2:5])
print(one_dim[:5])
print(one_dim[-5:])

[-0.3 -0.2 -0.1]
[ 1.  -0.4 -0.3 -0.2 -0.1]
[0.2 0.3 0.4 0.5 0.6]


In [47]:
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [46]:
two_dim[:2, :2]

array([[-1,  5],
       [ 7,  6]])

In [48]:
two_dim[:, 1:3]

array([[ 5,  2],
       [ 6,  5],
       [ 6, -1]])

### 2.5.3 Reshaping of arrays: Changing the shape of a given array

In [49]:
one_dim

array([ 1. , -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,  0.2,  0.3,  0.4,  0.5,
        0.6])

In [50]:
one_dim.reshape(4, 3)

array([[ 1. , -0.4, -0.3],
       [-0.2, -0.1,  0. ],
       [ 0.1,  0.2,  0.3],
       [ 0.4,  0.5,  0.6]])

In [51]:
two_dim

array([[-1,  5,  2,  4],
       [ 7,  6,  5,  5],
       [ 1,  6, -1, -1]])

In [53]:
two_dim.flatten()

array([-1,  5,  2,  4,  7,  6,  5,  5,  1,  6, -1, -1])